object Version {
    const val androidX = "1.8.0"
    const val appCompat = "1.4.2"
    const val constraintLayout = "2.1.4"
    const val coroutine = "1.3.9"
    const val compose = "1.1.1"
    const val composeAct = "1.4.0"
    const val composeViewModel = "2.4.1"
    const val espresso = "3.4.0"
    const val splash = "1.0.0-beta02"
    const val navigation = "2.4.2"
    const val material = "1.6.1"
    const val junit = "4.13.2"
    const val junitExt = "1.1.3"
    const val lifecycle = "2.4.0"
}